const IMAGES = {
  slide1: require("./slide1.png"),
  slide2: require("./slide2.png"),
  applogo: require("./applogo.png"),
  randomUser1: require("./randomUser1.png"),
  randomUser2: require("./randomUser2.png"),
  dummyEventImage: require("./dummyEventImage.png"),
  ColorPickerIcon: require("./colorPickerIcon.png"),
  qrCodeImage: require("./QrCode.png"),
  CodyProfile: require("./CodyProfile.png"),
  flameOverlay: require("./flameOverlay.png"),
  likeOverlay: require("./likeOverlay.png"),
  nopeOverlay: require("./nopeOverlay.png"),
  chatBackground: require("./chatBackground.png"),
  BaccvsSpecial1: require("./BaccvsSpecial1.png"),
  BaccvsSpecial2: require("./BaccvsSpecial2.png"),
  BaccvsSpecial3: require("./BaccvsSpecial3.png"),
  BaccvsSpecial4: require("./BaccvsSpecial4.png"),
  BaccvsSpecial5: require("./BaccvsSpecial5.png"),
  BaccvsSpecial6: require("./BaccvsSpecial6.png"),
  BaccvsSpecial7: require("./BaccvsSpecial7.png"),
  BaccvsSpecial8: require("./BaccvsSpecial8.png"),
  BaccvsSpecial9: require("./BaccvsSpecial9.png"),
  BaccvsSpecial10: require("./BaccvsSpecial10.png"),
  BaccvsSpecial11: require("./BaccvsSpecial11.png"),
  BaccvsSpecial12: require("./BaccvsSpecial12.png"),
  BaccvsSpecial13: require("./BaccvsSpecial13.png"),
  BaccvsSpecial14: require("./BaccvsSpecial14.png"),
  BaccvsSpecial15: require("./BaccvsSpecial15.png"),
  BubbbleImage: require("./Bubblesimg.png"),
  StarBoy: require("./starBoy.png"),
  Melodies: require("./melodies.png"),
  GlowGroove: require("./glowGrooveImg.png"),
  RhtythmNight: require("./rhtythmImg.png"),
  userFeedBackImg: require("./userFeedBackImg.png"),
  hostImage: require("./hostImg.png"),
  StarImage: require("./StarImages.png"),
  AlcoholCup: require("./AlcoholCup.png"),
  LeoImage: require("./LeoImage.png"),
  SmokingImage: require("./SmokingImage.png"),
  DjRole: require("./DjRole.png"),
  PromoterRole: require("./PromoterRole.png"),
  NightClubRole: require("./NightClubRole.png"),
};

export default IMAGES;
