import { Platform, StyleSheet } from "react-native";
import { horizontalScale, hp, verticalScale } from "../../Utilities/Metrics";
import COLORS from "../../Utilities/Colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
  },

  paginationContainer: {
    position: "absolute",
    bottom: 20,
    right: 10,
    backgroundColor: COLORS.blackPink,
    borderWidth: 1,
    borderColor: COLORS.pinklight,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 15,
  },
  paginationText: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
  imageContainer: {},
  eventImage: {
    width: "100%",
    height: hp(22),
    resizeMode: "cover",
  },
  overlay: {
    backgroundColor: COLORS.grey,
    borderRadius: 20,
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(5),
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(3),
    borderWidth: 1,
    borderColor: COLORS.voilet,
  },
  detailsContainer: {
    padding: horizontalScale(15),
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: verticalScale(5),
    gap: horizontalScale(10),
  },
  infoRow1: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: verticalScale(5),
    gap: horizontalScale(5),
  },
  inlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(5),
  },
  tagItem: {
    borderRadius: 20,
    paddingVertical: verticalScale(5),
    paddingHorizontal: horizontalScale(10),
    marginRight: horizontalScale(7),
    justifyContent: "center",
    alignItems: "center",
  },
  avatarStack: {
    paddingVertical: verticalScale(15),
    marginBottom: verticalScale(10),
    flexDirection: "row",
    position: "relative",
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.white,
    position: "absolute",
    backgroundColor: COLORS.grey,
  },
  moreAvatars: {
    backgroundColor: COLORS.voilet,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  hostContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.inputColor,
    paddingHorizontal: horizontalScale(15),
    marginHorizontal: horizontalScale(15),
    borderRadius: 15,
  },

  socialIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(10),
  },
  iconRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(5),
  },
  outerContainer: {
    backgroundColor: COLORS.inputColor,
    borderRadius: 15,
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(15),
    margin: verticalScale(15),
  },
  outerContainer1: {
    backgroundColor: COLORS.inputColor,
    borderRadius: 15,
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(15),
    marginHorizontal: horizontalScale(15),
  },
  header: {
    color: COLORS.white,
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  ticketContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: verticalScale(10),
  },
  ticketBox: {
    flex: 1,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: COLORS.voilet,
    paddingVertical: 10,
    gap: verticalScale(5),
  },
  BuyTicketBtn: {
    backgroundColor: COLORS.LinearPink,
    paddingVertical: verticalScale(10),
    paddingHorizontal: horizontalScale(15),
    alignItems: "center",
    alignSelf: "flex-end",
    borderRadius: 25,
    margin: verticalScale(15),
  },
  crossContainer: {
    position: "absolute",
    alignItems: "center",
    top: 32,
  },
  crossLineRotatePositive: {
    position: "absolute",
    width: 100,
    height: 1,
    backgroundColor: COLORS.lightBrown,
    transform: [{ rotate: "35deg" }],
  },
  crossLineRotateNegative: {
    position: "absolute",
    width: 100,
    height: 1,
    backgroundColor: COLORS.lightBrown,
    transform: [{ rotate: "-35deg" }],
  },
  button: {
    backgroundColor: COLORS.Brown,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.white,
  },
  freeEventContainer: {
    backgroundColor: "rgba(232, 127, 161, 0.1)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.primaryPink,
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(15),
    marginVertical: verticalScale(10),
  },
  freeEventContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ticketsSection: {
    marginTop: verticalScale(12),
    paddingVertical: verticalScale(10),
    borderTopWidth: 1,
    borderTopColor: COLORS.voilet,
  },
  ticketButtonsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: horizontalScale(10),
  },
  ticketButton: {
    backgroundColor: COLORS.likepink,
    paddingVertical: verticalScale(10),
    paddingHorizontal: horizontalScale(14),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minWidth: horizontalScale(80),
  },
  fixedTicketSection: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
    borderTopWidth: 1,
    borderTopColor: COLORS.voilet,
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(12),
    paddingHorizontal: horizontalScale(15),
  },
  fixedTicketContent: {
    gap: verticalScale(10),
  },
  fixedTicketScrollView: {
    marginTop: verticalScale(8),
  },
  fixedTicketScroll: {
    gap: horizontalScale(10),
    paddingRight: horizontalScale(15),
  },
  fixedTicketButton: {
    backgroundColor: COLORS.likepink,
    paddingVertical: verticalScale(12),
    paddingHorizontal: horizontalScale(16),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minWidth: horizontalScale(85),
    gap: verticalScale(3),
  },
});

export default styles;
