import { StyleSheet } from "react-native";
import COLORS from "../../Utilities/Colors";
import { horizontalScale, verticalScale } from "../../Utilities/Metrics";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
    gap: verticalScale(20),
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(10),
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(20),
  },
  contentContainer: {
    flex: 1,
    gap: verticalScale(15),
    marginVertical: verticalScale(25),
  },
  ticketOptionsContainer: {
    flexDirection: "row",
    gap: horizontalScale(10),
  },
  ticketInfoContainer: {
    position: "relative",
    borderRadius: 10,
    alignSelf: "flex-start",
    zIndex: 10,
  },
  ticketContent: {
    backgroundColor: COLORS.inputColor,
    alignItems: "center",
    justifyContent: "center",
    gap: verticalScale(10),
    paddingHorizontal: horizontalScale(30),
    paddingVertical: verticalScale(10),
    borderRadius: 10,
  },
  leftNotch: {
    position: "absolute",
    left: -2.1,
    top: "50%",
    transform: [{ translateY: -verticalScale(10) }],
    backgroundColor: COLORS.appBackground,
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
    zIndex: 100,
    height: verticalScale(20),
    width: verticalScale(10),
    borderColor: COLORS.darkPink,
    borderLeftColor: "transparent",
    borderWidth: 2,
  },
  rightNotch: {
    position: "absolute",
    right: -2.1,
    top: "50%",
    transform: [{ translateY: -verticalScale(10) }],
    backgroundColor: COLORS.appBackground,
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    zIndex: 100,
    height: verticalScale(20),
    width: verticalScale(10),
    borderColor: COLORS.darkPink,
    borderRightColor: "transparent",
    borderWidth: 2,
  },
  leftNotchHidden: {
    position: "absolute",
    left: -2.1,
    top: "50%",
    transform: [{ translateY: -verticalScale(10) }],
    backgroundColor: COLORS.appBackground,
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
    zIndex: 100,
    height: verticalScale(20),
    width: verticalScale(10),
  },
  rightNotchHidden: {
    position: "absolute",
    right: -2.1,
    top: "50%",
    transform: [{ translateY: -verticalScale(10) }],
    backgroundColor: COLORS.appBackground,
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    zIndex: 100,
    height: verticalScale(20),
    width: verticalScale(10),
  },
  quantityContainer: {
    backgroundColor: COLORS.inputColor,
    paddingVertical: verticalScale(16),
    paddingHorizontal: horizontalScale(16),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 16,
  },
  quantitySelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(20),
    backgroundColor: COLORS.inputColor,
    padding: 10,
    borderWidth: 2,
    borderColor: COLORS.voilet,
    borderRadius: 10,
  },
  quantityButton: {
    backgroundColor: COLORS.LinearPink,
    borderRadius: 100,
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  benefitsContainer: {
    gap: verticalScale(20),
    backgroundColor: COLORS.inputColor,
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(15),
    borderRadius: 16,
  },
  benefitsList: {
    rowGap: verticalScale(10),
  },
  benefitItem: {
    flexDirection: "row",
    gap: horizontalScale(10),
    alignItems: "center",
  },
  footerContainer: {
    gap: verticalScale(20),
  },
  termsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(20),
  },
  checkbox: {
    height: 20,
    width: 20,
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  divider: {
    borderBottomWidth: 1,
    borderColor: COLORS.voilet,
  },
  subtotalContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  subtotalTextContainer: {
    gap: verticalScale(5),
  },
  buyButton: {
    paddingVertical: verticalScale(12),
    paddingHorizontal: horizontalScale(50),
    borderRadius: verticalScale(20),
  },
  ticketScrollView: {
    maxHeight: verticalScale(70),
  },
});

export default styles;
