import ICONS from "../Assets/Icons";
import IMAGES from "../Assets/Images";
import { IndividualEvents } from "../Typings/type";
import COLORS from "../Utilities/Colors";

export const matchData: IndividualEvents[] = [
  {
    id: "1",
    type: "individual",
    name: "Jerome",
    message: "Jerome has superliked you.",
    icon: ICONS.Fire,
    date: "24/12/2024",
    backgroundColor: COLORS.primaryPink,
  },
  {
    id: "2",
    type: "group",
    name: "Friends With Benefits",
    message: "You’re in! Have fun.",
    members: [
      IMAGES.CodyProfile,
      IMAGES.slide2,
      IMAGES.slide1,
      IMAGES.CodyProfile,
    ],
    date: "24/12/2024",
  },
  {
    id: "3",
    type: "individual",
    name: "Cody",
    message: "Cody liked you.",
    icon: ICONS.HurtIcon,
    date: "24/12/2024",
    backgroundColor: COLORS.likepink,
  },
  {
    id: "4",
    type: "group",
    name: "Sunset Seekers",
    message: "You’re in! Have fun.",
    members: [
      IMAGES.CodyProfile,
      IMAGES.slide2,
      IMAGES.slide1,
      ICONS.QuestionmarkIcon,
    ],
    date: "24/12/2024",
    borderBottom: true,
  },
  {
    id: "5",
    type: "group",
    name: "The Night Owls",
    message: "You’re in! Have fun.",
    members: [
      IMAGES.CodyProfile,
      IMAGES.slide2,
      IMAGES.slide1,
      ICONS.QuestionmarkIcon,
    ],
    date: "24/12/2024",
    borderBottom: true,
  },
  {
    id: "6",
    type: "individual",
    name: "Lida",
    message: "You refused the match.",
    icon: ICONS.StarIcon,
    date: "24/12/2024",
    backgroundColor: "transparent",
  },
  {
    id: "7",
    type: "individual",
    name: "Helen",
    message: "Helen liked you.",
    icon: ICONS.HurtIcon,
    date: "24/12/2024",
    backgroundColor: COLORS.likepink,
  },
  {
    id: "8",
    type: "group",
    name: "Travel Buddies",
    message: "You’re in! Get ready to explore.",
    members: [IMAGES.slide1, IMAGES.slide2, ICONS.QuestionmarkIcon],
    date: "25/12/2024",
    borderBottom: false,
  },
  {
    id: "9",
    type: "individual",
    name: "Sophia",
    message: "Sophia liked your profile.",
    icon: ICONS.HurtIcon,
    date: "25/12/2024",
    backgroundColor: COLORS.likepink,
  },
  {
    id: "10",
    type: "group",
    name: "Food Lovers",
    message: "You’re in! Let’s eat.",
    members: [IMAGES.CodyProfile, IMAGES.slide1, IMAGES.slide2],
    date: "26/12/2024",
  },
  {
    id: "11",
    type: "individual",
    name: "Leo",
    message: "Leo has superliked you.",
    icon: ICONS.Fire,
    date: "26/12/2024",
    backgroundColor: COLORS.primaryPink,
  },
  {
    id: "12",
    type: "group",
    name: "Adventure Club",
    message: "You’re in! Gear up.",
    members: [IMAGES.slide1, IMAGES.slide2, IMAGES.CodyProfile],
    date: "27/12/2024",
  },
  {
    id: "13",
    type: "individual",
    name: "Mia",
    message: "Mia sent you a heart.",
    icon: ICONS.StarIcon,
    date: "27/12/2024",
    backgroundColor: "transparent",
  },
  {
    id: "14",
    type: "group",
    name: "Night Crawlers",
    message: "You’re in! Let's party.",
    members: [IMAGES.CodyProfile, ICONS.QuestionmarkIcon, IMAGES.slide2],
    date: "28/12/2024",
  },
  {
    id: "15",
    type: "individual",
    name: "Oliver",
    message: "Oliver liked your vibe.",
    icon: ICONS.HurtIcon,
    date: "28/12/2024",
    backgroundColor: COLORS.likepink,
  },
];
