import { StyleSheet } from "react-native";
import COLORS from "../../Utilities/Colors";
import { horizontalScale, verticalScale } from "../../Utilities/Metrics";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
  },
  safeAreaCont: {
    flex: 1,
    paddingVertical: verticalScale(16),
    gap: verticalScale(10),
  },
  innerContainer: {
    paddingHorizontal: horizontalScale(10),
    gap: verticalScale(20),
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerIcons: {
    flexDirection: "row",
    gap: horizontalScale(20),
    alignItems: "center",
  },
  followbtn: {
    backgroundColor: COLORS.mediuumPink,
    borderRadius: 20,
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(7),
  },
  followBtn: {
    backgroundColor: COLORS.primaryPink,
    paddingVertical: verticalScale(6),
    paddingHorizontal: horizontalScale(16),
    borderRadius: 20,
  },
  followingBtn: {
    backgroundColor: "transparent",
    paddingVertical: verticalScale(6),
    paddingHorizontal: horizontalScale(16),
    borderWidth: 1,
    borderColor: "grey",
  },
  memberItem: {
    paddingVertical: verticalScale(8),
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(10),
  },
  Memberlist: {
    backgroundColor: COLORS.darkVoilet,
    paddingVertical: verticalScale(10),
    borderRadius: 10,
    paddingHorizontal: horizontalScale(10),
    gap: verticalScale(10),
  },
  loaderContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    backgroundColor: COLORS.appBackground,
  },
  nopeOverlay: {
    position: "absolute",
    top: "25%",
    left: "25%",
    width: 200,
    height: 200,
    resizeMode: "contain",
    transform: [{ translateX: -100 }, { translateY: -100 }],
    zIndex: 10,
  },
  flameOverlay: {
    position: "absolute",
    top: "40%",
    left: "50%",
    width: 200,
    height: 200,
    resizeMode: "contain",
    transform: [{ translateX: -100 }, { translateY: -100 }],
    zIndex: 10,
  },
  likeOverlay: {
    position: "absolute",
    top: "15%",
    right: "10%",
    width: 120,
    height: 120,
    resizeMode: "contain",
    transform: [{ translateX: -60 }],
    zIndex: 10,
  },
  starOverlay: {
    position: "absolute",
    width: 50,
    height: 50,
    top: 0,
    resizeMode: "contain",
    zIndex: 10,
  },
  actionButton: {
    backgroundColor: COLORS.blackPink,
    borderRadius: 100,
    padding: verticalScale(18),
  },
  actionContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    width: "100%",
    zIndex: 1,
  },
  detaillist: {
    backgroundColor: COLORS.darkVoilet,
    paddingVertical: 20,
    marginVertical: verticalScale(10),
    borderRadius: 10,
    paddingHorizontal: horizontalScale(10),
  },
  identityCardHorizontal: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(8),
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(6),
  },
  identityCardIconSmall: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  identityCardTextGroup: {
    flexDirection: "column",
    justifyContent: "center",
    maxWidth: horizontalScale(100),
  },
  habitsSection: {
    marginVertical: verticalScale(10),
  },
  habitItemHorizontal: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(5),
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(6),
  },
  habitItemIcon: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  habitItemTextGroup: {
    flexDirection: "column",
    justifyContent: "center",
  },
  aboutContainer: {
    backgroundColor: COLORS.darkVoilet,
    padding: horizontalScale(20),
    borderRadius: 10,
  },
  profileSelectorContainer: {
    paddingVertical: verticalScale(10),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.darkVoilet,
  },
  profileSelectorContent: {
    paddingHorizontal: horizontalScale(10),
    gap: horizontalScale(10),
  },
  profileSelectorBtn: {
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(16),
    borderRadius: 20,
    backgroundColor: COLORS.darkVoilet,
    borderWidth: 1,
    borderColor: "transparent",
  },
  profileSelectorBtnActive: {
    backgroundColor: COLORS.primaryPink,
    borderColor: COLORS.primaryPink,
  },
  professionalContent: {
    paddingHorizontal: horizontalScale(10),
    paddingVertical: verticalScale(15),
  },
  packageCard: {
    backgroundColor: COLORS.darkVoilet,
    padding: horizontalScale(15),
    borderRadius: 10,
    marginBottom: verticalScale(10),
    gap: verticalScale(8),
  },
  packageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statBox: {
    flex: 1,
    backgroundColor: COLORS.darkVoilet,
    borderRadius: horizontalScale(10),
    alignItems: "center",
    paddingVertical: verticalScale(15),
    gap: verticalScale(5),
  },
});

export default styles;
